basePath: /api/v1
definitions:
  dto.CreateUserRequest:
    properties:
      status:
        description: 'required: true'
        enum:
        - active
        - inactive
        type: string
      task:
        description: 'required: true'
        maxLength: 300
        minLength: 1
        type: string
    required:
    - status
    - task
    type: object
  dto.UpdateUserRequest:
    properties:
      status:
        description: 'required: true'
        enum:
        - active
        - inactive
        type: string
      task:
        description: 'required: true'
        maxLength: 300
        minLength: 1
        type: string
    required:
    - status
    - task
    type: object
info:
  contact: {}
  description: example of artifact web-framework
  title: Artifact Boilerplate
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: All users
      parameters:
      - description: Page
        in: query
        name: page
        type: string
      - description: Limit
        in: query
        name: limit
        type: string
      - description: Status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "401":
          description: ""
      summary: all users
      tags:
      - User
    post:
      consumes:
      - application/json
      description: create a user
      parameters:
      - description: Create User Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "401":
          description: ""
      summary: create a user
      tags:
      - User
  /users/{userId}:
    delete:
      consumes:
      - application/json
      description: delete a user
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "422":
          description: ""
      summary: delete a user
      tags:
      - User
    get:
      consumes:
      - application/json
      description: User Details
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "401":
          description: ""
      summary: user details
      tags:
      - User
    put:
      consumes:
      - application/json
      description: update a user
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      - description: Update User Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "401":
          description: ""
      summary: update a user
      tags:
      - User
swagger: "2.0"
